linters:
  enable-all: true
  disable:
    - funlen
    - wsl
    - gochecknoglobals
#    - dupl
#    - lll
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 40
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 90
issues:
  exclude-rules:
    - text: "G204: Subprocess launched with function call as argument or cmd arguments"
      linters:
        - gosec
