language: go

go:
  - 1.x

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1

script:
  - go test -v ./...
  - golangci-lint run

before_deploy:
  - export REPO_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f2)
  - go build -o ${REPO_NAME}
  - tar -czvf ${REPO_NAME}_${TRAVIS_TAG}_linux_amd64.tar.gz ${REPO_NAME}
deploy:
  provider: releases
  api_key:
    secure: y84ZLdSHuM/jMur9ja59bqbLYJ9iU/o0wiMhhLsc83po0lwq50xE5u/xUK4vpggkqJsXuwtGrji7w/KbY9jb9OYRBvP5RQMTyGNwHswGew3crKHVniCaooK5BTPayu+e+Q9k40K1V/2YjC9GSBpLTclkyl1M4ZQ5Jouh3tO3Bav3X3cspc23aXiXAOr3YgnVkExr5XZrUUBlnMi9pHu5sXydN2sstaPc3kbq3Gn3c0gBqWk2kw+hLL2njFC07nXZ7d1v5SiYRGLbbBRtPorAoSo+JtTMqmInRkNEDXXJDZ3KINsqHKiPSr1YqtKiCtVNqWxms4255kvwkqZq2/ai/4Q0VLTtwqUBfasJHUioovR2BSWEJjsoLrPW7w9tTL/nKi9hpHiJawi9jSdOg74HQ0jURziDm4cPJJKtEBlAq/cJcC0CPNdwh2vq+FD4wZ9srCEvseWW1IycPbEcmYDivgpNFgJX3Zqv07MYHT+A2FBcy5pFjR0MIVy0sr8xzqIw+Ne9RWOpmdr4aFFwIwjR7NiqAb+sClN0IhDB8faf0ZJEyqwxf0eBgKvrtSUBRl68N5Llw1bv0F8Brg249A4RdWYZ0AJM1sTGPRYujy7HnEReCAMILg4txWbBOiSaLXupAEdZKhSSC8A6rbawRVLa1SpfQvSRnpgvZxhLe4oTD34=
  file: ${REPO_NAME}_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
